import { CurrencyCode, CurrencyConfig, CalculatorInput, PresetScenario } from '@/types/etsy';
export {
  ETSY_TRANSACTION_FEE_RATE,
  ETSY_LISTING_FEE_USD,
  ETSY_OFFSITE_ADS_RATES,
  ETSY_CURRENCY_CONVERSION_RATE,
  ETSY_OTHER_APPLICABLE_FEES_DEFAULT,
  COUNTRY_FEES as COUNTRIES,
  getCountryFeeConfig,
} from './fees';

export const CURRENCIES: Record<CurrencyCode, CurrencyConfig> = {
  USD: { code: 'USD', symbol: '$', name: 'US Dollar (USD)', position: 'before', decimals: 2 },
  EUR: { code: 'EUR', symbol: '€', name: 'Euro (EUR)', position: 'before', decimals: 2 },
  GBP: { code: 'GBP', symbol: '£', name: 'British Pound (GBP)', position: 'before', decimals: 2 },
  CAD: { code: 'CAD', symbol: 'CA$', name: 'Canadian Dollar (CAD)', position: 'before', decimals: 2 },
  AUD: { code: 'AUD', symbol: 'A$', name: 'Australian Dollar (AUD)', position: 'before', decimals: 2 },
  NZD: { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar (NZD)', position: 'before', decimals: 2 },
  CHF: { code: 'CHF', symbol: 'CHF ', name: 'Swiss Franc (CHF)', position: 'before', decimals: 2 },
  SEK: { code: 'SEK', symbol: 'kr ', name: 'Swedish Krona (SEK)', position: 'after', decimals: 2 },
  NOK: { code: 'NOK', symbol: 'kr ', name: 'Norwegian Krone (NOK)', position: 'after', decimals: 2 },
  DKK: { code: 'DKK', symbol: 'kr ', name: 'Danish Krone (DKK)', position: 'after', decimals: 2 },
  PLN: { code: 'PLN', symbol: ' zł', name: 'Polish Złoty (PLN)', position: 'after', decimals: 2 },
  JPY: { code: 'JPY', symbol: '¥', name: 'Japanese Yen (JPY)', position: 'before', decimals: 0 },
  SGD: { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar (SGD)', position: 'before', decimals: 2 },
  HKD: { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar (HKD)', position: 'before', decimals: 2 },
  INR: { code: 'INR', symbol: '₹', name: 'Indian Rupee (INR)', position: 'before', decimals: 2 },
};

export const DEFAULT_CALCULATOR_INPUT: CalculatorInput = {
  productType: 'digital',
  currency: 'USD',
  regularPrice: 35.0,
  discount: 10,
  listingType: 'paid',
  productCost: 0,
  packagingCost: 0,
  shippingCharged: 0,
  actualShippingCost: 0,
  country: 'US',
  etsyAdsEnabled: false,
  etsyAdsCost: 0,
  offsiteAdsEnabled: false,
  offsiteAdsTier: 'standard',
  otherSellerCosts: 0,
};

export const PRESET_SCENARIOS: PresetScenario[] = [
  {
    id: 'digital-planner',
    title: 'Digital Planner / Printable',
    subtitle: 'Zero shipping, high margin digital download',
    icon: 'FileSpreadsheet',
    data: {
      productType: 'digital',
      regularPrice: 15.0,
      discount: 20,
      listingType: 'paid',
      productCost: 0.5,
      packagingCost: 0,
      shippingCharged: 0,
      actualShippingCost: 0,
      etsyAdsEnabled: false,
      offsiteAdsEnabled: false,
    },
  },
  {
    id: 'handmade-mug',
    title: 'Handmade Ceramic Mug',
    subtitle: 'Physical item with packaging & standard postage',
    icon: 'Coffee',
    data: {
      productType: 'physical',
      regularPrice: 32.0,
      discount: 0,
      listingType: 'paid',
      productCost: 7.0,
      packagingCost: 2.5,
      shippingCharged: 6.0,
      actualShippingCost: 5.8,
      etsyAdsEnabled: false,
      offsiteAdsEnabled: false,
    },
  },
  {
    id: 'custom-tshirt',
    title: 'Custom POD T-Shirt',
    subtitle: 'Print-on-demand with Etsy Ads campaign',
    icon: 'Shirt',
    data: {
      productType: 'physical',
      regularPrice: 28.0,
      discount: 15,
      listingType: 'paid',
      productCost: 11.5,
      packagingCost: 0.5,
      shippingCharged: 4.5,
      actualShippingCost: 4.5,
      etsyAdsEnabled: true,
      etsyAdsCost: 3.5,
      offsiteAdsEnabled: false,
    },
  },
  {
    id: 'jewelry-offsite',
    title: 'Silver Jewelry (Offsite Ads)',
    subtitle: 'High-ticket item with Etsy Offsite Ads enabled',
    icon: 'Sparkles',
    data: {
      productType: 'physical',
      regularPrice: 75.0,
      discount: 10,
      listingType: 'paid',
      productCost: 16.0,
      packagingCost: 3.0,
      shippingCharged: 0,
      actualShippingCost: 4.8,
      etsyAdsEnabled: false,
      offsiteAdsEnabled: true,
      offsiteAdsTier: 'standard',
    },
  },
];
